ssh:
  arthas:
    server: "cd /tmp && curl -O https://arthas.aliyun.com/arthas-boot.jar && sudo su - app -c 'java -jar /tmp/arthas-boot.jar'\n"
    # kubernetes: "java -jar /home/app/arthas-boot.jar\n"
  shell:
    enable: true
    # 'simple' or 'security'
    authentication: security
    # if authentication set to 'security' the AuthenticationProvider bean name
    # if not specified and only one AuthenticationProvider bean is present in the context, it will be used
    confirmation-words:
      - y
      - yes
    # since 1.4.0, set enable to false to disable following default commands
    commands:
      actuator:
        create: false
        enable: false
        restricted: false
        # empty by default
        excludes:
          - ...
        authorized-roles:
          - ACTUATOR
      # since 1.4.0
      jmx:
        create: false
        enable: false
        restricted: false
        authorized-roles:
          - ADMIN
      system:
        create: false
        enable: false
        restricted: false
        authorized-roles:
          - ADMIN
      # since 1.4.0
      datasource:
        create: false
        enable: false
        restricted: false
        authorized-roles:
          - ADMIN
        excludes:
          - datasource-list
          - datasource-properties
          - datasource-query
          - datasource-update
      postprocessors:
        create: true
        enable: true
        restricted: false
      # since 1.3.0, command which allows you to list ssh sessions, and stop them
      manage-sessions:
        create: false
        enable: false
        restricted: false
        authorized-roles:
          - ADMIN
      # since 1.5.0
      tasks:
        create: true
        enable: false
        restricted: false
        authorized-roles:
          - ADMIN
    display-banner: true
    # to use ExtendedFileValueProviderTest instead of spring shell FileValueProvider for all File option parameters
    # if set to false, it still can be used via '@ShellOption(valueProvider = ExtendedFileValueProviderTest.class) File file'
    extended-file-provider: true
    history-file: ${home}/opscloud-data/ssh-server/sshShellHistory.log
    # since 1.3.0, set to false to have one file per user (<history-directory>/sshShellHistory-<user>.log)
    shared-history: true
    # since 1.3.0, only if shared-history is set to false
    history-directory: ${home}/opscloud-data/ssh-server
    host-key-file: ${home}/opscloud-data/ssh-server/hostKey.ser
    # displayed in log if generated
    port: 2222
    prompt:
      # in enum: com.github.fonimus.ssh.shell.PromptColor (black, red, green, yellow, blue, magenta, cyan, white, bright)
      color: white
      text: 'opscloud shell>'
      local:
        # since 1.2.1, to let default local spring shell prompt when application starts
        enable: false
project:
  version: 4.0
