logging:
  level:
    # swagger 警告日志忽略
    io.swagger.models.parameters.AbstractSerializableParameter: error
log:
  file:
    path: ${HOME}/logs

opscloud:
  version: 4.0.9
  dataPath: ${HOME}/opscloud-data
  createUser:
    roles:
      - base
    userGroups:
  outapi:
    workorder:
      approval: "http://127.0.0.1:8080/api/out/ticket/approve?ticketId=%s&username=%s&approvalType=%s&token=%s";
# auditPath 审计日志目录
# openAudit :on 开启审计日志 off 关闭审计日志
terminal:
  auditPath: ${HOME}/opscloud-data/ssh/audit
  openAudit: on

# 白名单配置
white:
  urls:
    - /*.js
    - /*.css
    - /*.jpg
    - /*.ico
    - /swagger-resources
    - /swagger-ui.html
    - /v2/api-docs
    - /doc.html
    - /api/ws/guacamole/tunnel
    - /api/ws/terminal
    - /api/ws/kubernetes/terminal
    - /api/ws/terminal/session/audit
    - /api/ws/server/task/play

spring:
  config:
    activate:
      on-profile:
        - github
  redis:
    host: redis.opscloud.com
    port: 6379
    password: 'v2TBjJP5QZEd3ah1'
    jedis:
      pool:
        max-wait: 5000
        max-idle: 20
        max-active: 100
        min-idle: 0
  datasource:
    druid:
      opscloud:
        url: jdbc:mysql://mysql.opscloud.com:3306/opscloud4-github?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useInformationSchema=true&tinyInt1isBit=true&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
        username: opscloud4_github
        password: '6Ln7N9uPYOyfNmF1'
        initial-size: 5
        min-idle: 5
        max-active: 20
        # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
        max-wait: 1000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        # 用来检测连接是否有效的sql
        validation-query: select 1
        # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
        test-while-idle: on
        # 申请连接时执行validationQuery检测连接是否有效, 默认true:检测,false:不检测
        test-on-borrow: off
        # 归还连接时执行validationQuery检测连接是否有效,默认false:不检测,ture:检测
        test-on-return: off
        # 打开PSCache(preparedStatement)，并且指定每个连接上PSCache的大小
        pool-prepared-statements: on
        # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
        max-pool-prepared-statement-per-connection-size: 20

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: 'org.jasypt.iv.NoIvGenerator'
    # 加密密钥，可以通过命令参数指定 `java -jar -Djasypt.encryptor.password=${password}`
    password: '1^Z!NxcB4s!0Sxz&URokZ6DdZnNn#acO#ELjM&kvun^LV!yCB%ec*^NJ%5xvCGlJ6&SHGtKN#Gs!fK%lq8aQYpfLlwkFrvQrcp1VzYGt74vdVcMmUk73%HCrOV07IZw0'